version: '3'

services:
  kube_forwards:
    build: .
    entrypoint: ['tail', '-f', '/dev/null']
    environment:
      - SERVICES=stock-service:3000
    ports:
      - 3000:3000
    volumes:
      - ~/.kube/config:/root/.kube/config
      - .:/code
    networks:
      - default

networks:
  default:
