version: '2'

services:
  kube_forwards:
    build: .
    entrypoint: ['tail', '-f', '/dev/null']
    environment:
      - SERVICES=authenticationservice:8000, srservice:8001:8000
    ports:
      - 8011:8000
      - 8012:8001
    volumes:
      - ~/.kube/config:/root/.kube/config
      - .:/code
    networks:
      - default

networks:
  default:
